### ISSUE TITLE
Package Identifier is missing when Publish if QoS > 0

### ISSUE THREAD

**Issue by yueyuzhao** [oliverlorenz/phpMqttClient#32]
Hello there, 
When publishing messages where `QoS > 0`, base on spec 2.3.1, it should have `Package Identifier`, while this library seems not sending it and in `packet/Publish.php`, `$messageId` is not used.

**Comment by yueyuzhao** [comment]
From spec 2.3.1

> SUBSCRIBE, UNSUBSCRIBE, and PUBLISH (in cases where QoS > 0) Control Packets MUST contain a non-zero 16-bit Packet Identifier [MQTT-2.3.1-1].

**Comment by oliverlorenz** [comment]
Hi!

thanks for your report, and it seems you are right. Unforgenally I currently don't have time to fix that, but I would appreciate a PR with that change and a simple test.

It seems the messageId is missing in general. In my opinion this should be fixed in `src/packet/ControlPacket.php`

Could you take that over?

**Comment by yueyuzhao** [comment]
Hi @oliverlorenz , thank you for this wonderful project, but after a deep research on the `MQTT` protocol, I found that adding `Package Identifier` is far from enough to publish messages where `Qos > 0`, the library need to response to not only `PublishAck` but also `PublishRelease` and more. 

This library is great but doesn't fulfill my needs, so I extract your codes into 2 repos and did some refactor and cleaning. Here is the new package [mqtt-packet](https://github.com/jndrm/mqtt-packet), and I sincerely hope you don't mind.

**Comment by jjok** [comment]
Hi @yueyuzhao. That feature hasn't been added yet. Feel free to do so.

**Comment by oliverlorenz** [comment]
Hi @yueyuzhao!

> hope you don't mind.

no worrys! :slightly_smiling_face: I appreciate that you put so much effort into that! That is simply amazing! :rocket: :sparkles: 

The only concern I have in the moment is, that we duplicate large parts of the code base here and the original project left with the bug. I mean you fixed that, but the result is currently only useful for you, because the glue code is missing (Maybe you can provide them in a PR?). 

I would love to split that up and make this project more professional in that way. And if we are already talking about: What about to move both projects in a common github organization and split up the code responsibilities in a general way? This makes the development easier and other people can rely on a better maintained project.

What do you think guys? @yueyuzhao @jjok 

If you agree to that, I would start to prepare that switch.

**Comment by jjok** [comment]
I think it's definitely no ideal to forking this codebase to add new features. That way we end up with 2 libraries, neither of which implement the full protocol.

@yueyuzhao Why not add the QOS features to this library?

Also, I don't think https://github.com/binsoul/net-mqtt-client-react was around when I started using this library. I assume it is more complete now than this one, so it may not be worth spending a lot of time on this one.

**Comment by yueyuzhao** [comment]
Hi @oliverlorenz, many thanks for your understandings. And I think it's a nice idea to create a github organization.

**Comment by yueyuzhao** [comment]
Hi @jjok, sorry for not adding the `Qos` feather to this library, but I don't have much time to do so.

> I think it's definitely no ideal to forking this codebase to add new features. That way we end up with 2 libraries, neither of which implement the full protocol.

Well, this library is targeting for the client side and that's enough. But when I need to implement a broker, I need to parse these packets again, and I don't think it's a best practice.
